task:
  type: "geonodes"


credentials:
  openai: openai_api.txt
  claude: 
  gemini:

input:
  text_prompt: 
  input_image: /home/richard/Documents/blendergym_test/bench_data/geometry19/renders/goal/render1.png
  target_code:

output:
  output_dir: "output/geometry19/"

run_config:
  blender_command: "infinigen/blender/blender"
  edit_style: "rewrite_code"
  num_tries: 1
  enable_visual_imagination: False 
  enable_hypothesis_reversion: True
  variants: 
    - "tune"
  tree_dims: 
    - "2x3"
  edit_generator_type: "GPT4V"
  state_evaluator_type: "GPT4V"

  max_concurrent_rendering_processes: 4
  max_concurrent_evaluation_requests: 2
  max_concurrent_generator_requests: 4

